config/routes.rb
Rails.application.routes.draw do
  root 'stories#index'

  devise_for :users

  resources :stories, only: [:index, :show] do
    member do
      put 'like', to: 'stories#upvote'
      put 'dislike', to: 'stories#downvote'
    end
  end

  resources :users do
    resources :comments
  end

  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
end

app/models/story.rb
require 'ruby-hackernews'

class Story < ActiveRecord::Base
  include RubyHackernews
  has_many :comments, dependent: :destroy
  validates :external_id, presence: true
  acts_as_votable

  def self.save_entries_from_hn
    entries = RubyHackernews::Entry.all(17).drop(10)
    increment = Story.maximum(:active_group) + 1

    stories = entries.map do |e|
      s = Story.find_or_initialize_by(external_id: e.id, url: e.link.href)
      s.external_id = e.id
      s.title = e.link.title
      s.url = e.link.href
      s.active_group = increment
      s.hn_score = e.voting.score
      s.save
      s
    end
    stories.select(&:persisted?)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    allowed = [:username, :first_name, :last_name]
    allowed.each do |field|
      devise_parameter_sanitizer.for(:sign_up) << field
      devise_parameter_sanitizer.for(:account_update) << field
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = current_user.comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = current_user.comments.find(params[:id])
    if !@comment
      redirect_to new_user_comment_path(current_user)
    end
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :story_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    Rails.cache.fetch("hn_data", expires_in: 5.minutes) do
      Story.save_entries_from_hn
    end
    increment = Story.maximum(:active_group)
    @stories = Story.where(active_group: increment)
  end

  def show
    @story = Story.find(params[:id])
    @comment = Comment.new(story: @story)
  end

  def upvote
    @story = Story.find(params[:id])
    @story.upvote_by current_user
    calculate_and_save_points
    redirect_to :back
  end

  def downvote
    @story = Story.find(params[:id])
    @story.downvote_by current_user
    calculate_and_save_points
    redirect_to :back
  end

  private

  def calculate_and_save_points
    upvotes = @story.get_upvotes.size
    downvotes = @story.get_downvotes.size
    @story.points = upvotes - downvotes
    @story.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message
  = f.hidden_field(:story_id, value: @comment.story_id)
  = f.text_area :body
  .actions = f.submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment
'|
= link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th
      th
      th
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.body
        td = comment.story.title
        td = comment.created_at
        td = link_to 'Show', user_comment_path(id: comment.id)
        td = link_to 'Edit', edit_user_comment_path(id: comment.id)
        td = link_to 'Destroy', comment, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

.row
  .large-12.columns
    table
      thead
        tr
          td Comment:
          td

      tbody
        tr
          td Id:
          td = @comment.id
        tr
          td Body:
          td = @comment.body
        tr
          td Created:
          td = @comment.created_at


= link_to 'Edit', edit_user_comment_path(id: @comment.id, user_id: current_user)
'|
= link_to 'Back', user_comments_path(user_id: current_user)
'|
= link_to 'Article', story_path(id: @comment.story_id)

app/views/layouts/_navbar.html.slim
nav.top-bar
  ul.title-area
    li.name
      h1
        = link_to 'Hacker500', root_path
  section.top-bar-section
    ul.right
      - if user_signed_in?
        li = link_to 'Account', edit_user_registration_path
        li = link_to 'Logout', destroy_user_session_path, :method=>'delete'
      - else
        li = link_to 'Login', new_user_session_path
        li = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Busy Giver
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render "layouts/navbar"
    .row
      .large-12.columns.padv50
        = display_flash_messages
      .large-12.columns
        = yield

app/views/pages/home.html.slim
h1 Home Page

app/views/stories/index.html.slim
.row
  .large-12.columns
    h1 Trending
.row
  .large-12.columns
    table
      thead
        tr
          th id
          th External ID
          th Article
          th Hacker500 Score
          th HN Score
      tbody
        - @stories.each do |s|
          tr
            td = s.id
            td = s.external_id
            td = link_to(s.title, story_path(s.id))
            td = s.points
            td = s.hn_score

app/views/stories/show.html.slim
.row
  .large-6.columns
    table.responsive
      tbody
        tr
          td Title:
          td = @story.title
        tr
          td Link:
          td = link_to(@story.url, @story.url)
        tr
          td Votes:
          td
            | Upvotes: &nbsp
            = @story.get_upvotes.size
            br
            | Downvotes: &nbsp
            = @story.get_downvotes.size
        tr
          td Vote:
          td
            = link_to('Upvote', like_story_path(@story.id), method: :put)
            br
            = link_to('Downvote', dislike_story_path(@story.id), method: :put)


  .large-6.columns
    h3 Comments
    - @story.comments.each do |comment|
      .row.comment
        .large-12.columns
          .row
            .large-6.columns
              strong = comment.user.username
            .large-6.columns.text-right
              i = time_ago_in_words(comment.created_at)
          .row
            .large-12.columns
              = comment.body
    h4 Leave Reply
    = render 'comments/form'
    / = link_to 'Tell us what you think', new_user_comment_path(story_id: @story.id, user_id: current_user.id)